version: '3.3'
services:
    backend:
        build:
            context: .
        command: node server.js
        volumes:
            - .:/app/
            - ../configuration/:/configuration
        ports:
            - '3001:3001'
